### ISSUE TITLE
Themes doesnt work with ISPConfig-3.1

### ISSUE THREAD

**Issue by smoonlee** [natanfelles/ispconfig-clean-theme#1]
Hi, Would it be possible to get this theme updated for ISPConfig 3.1

**Comment by natanfelles** [comment]
Yes. Would you like to start doing this?

ISPConfig 3.1 uses Bootstrap 3, with SASS, so it would be enough to update some variables and build.

At the moment I'm busy with other services. If you want to send a PR I will be very happy.

The source is here: https://git.ispconfig.org/ispconfig/ispconfig3/tree/master/interface/web/themes/default/assets/stylesheets
